spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}
            allowedHeaders: "*"
            allowedMethods: "*"
            allowCredentials: ${CORS_ALLOWED_CREDENTIALS:true}

      routes:
        - id: auth
          uri: http://auth-service:8082
          predicates:
            - Path=/auth/**

        - id: accounts
          uri: http://account-service:8083
          predicates:
            - Path=/accounts/**

        - id: products
          uri: http://product-service:8084
          predicates:
            - Path=/products/**

        - id: exchange
          uri: http://exchange-service:8081
          predicates:
            - Path=/exchange/**

        - id: insper
          uri: https://www.insper.edu.br
          predicates:
            - Path=/insper/**

server:
  port: 8080

auth:
  service:
    solve-url: ${AUTH_SERVICE_SOLVE_URL:http://auth-service:8082/auth/solve}

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: info
    store: debug
    org.springframework.cloud.gateway: debug
